# -*- coding: utf-8 -*-
# snapshottest: v1 - https://goo.gl/zC4yUc
from __future__ import unicode_literals

from snapshottest import GenericRepr, Snapshot


snapshots = Snapshot()

snapshots['test_load_stops 1'] = [
    GenericRepr("Stop(atco_code='0100BRP90310', naptan_code='bstgwpa', plate_code='', cleardown_code='', common_name='Temple Meads Stn', common_name_lang='', short_common_name='Temple Meads Stn', short_common_name_lang='', landmark='', landmark_lang='', street='Redcliffe Way', street_lang='', crossing='', crossing_lang='', indicator='T3', indicator_lang='', bearing='SE', nptg_locality_code='N0077020', nptg_locality_name='Temple Meads', parent_locality_name='', grand_parent_locality_name='', town='', town_lang='', suburb='', suburb_lang='', locality_centre=False, grid_type='UKOS', easting=359396, northing=172388, longitude=-2.58569, latitude=51.44901, stop_type='BCT', bus_stop_type='MKD', timing_status='OTH', default_wait_time='', notes='', notes_lang='', administrative_area_code='009', creation_date_time=datetime.datetime(2009, 8, 25, 0, 0), modification_date_time=datetime.datetime(2019, 9, 13, 10, 41, 24), revision_number=92, modification='new', status='active')"),
    GenericRepr("Stop(atco_code='0100BRP90311', naptan_code='bstgwpm', plate_code='', cleardown_code='', common_name='Temple Meads Stn', common_name_lang='', short_common_name='Temple Meads Stn', short_common_name_lang='', landmark='', landmark_lang='', street='Victoria Street', street_lang='', crossing='', crossing_lang='', indicator='T7', indicator_lang='', bearing='NW', nptg_locality_code='N0077020', nptg_locality_name='Temple Meads', parent_locality_name='', grand_parent_locality_name='', town='', town_lang='', suburb='', suburb_lang='', locality_centre=False, grid_type='UKOS', easting=359403, northing=172513, longitude=-2.5856, latitude=51.45014, stop_type='BCT', bus_stop_type='MKD', timing_status='OTH', default_wait_time='', notes='', notes_lang='', administrative_area_code='009', creation_date_time=datetime.datetime(2009, 8, 25, 0, 0), modification_date_time=datetime.datetime(2019, 9, 13, 10, 41, 38), revision_number=73, modification='new', status='active')"),
    GenericRepr("Stop(atco_code='010000056', naptan_code='bstpjgw', plate_code='', cleardown_code='', common_name='Temple Meads Stn', common_name_lang='', short_common_name='Temple Meads Stn', short_common_name_lang='', landmark='', landmark_lang='', street='Temple Gate', street_lang='', crossing='', crossing_lang='', indicator='T2', indicator_lang='', bearing='N', nptg_locality_code='N0077020', nptg_locality_name='Temple Meads', parent_locality_name='', grand_parent_locality_name='', town='', town_lang='', suburb='', suburb_lang='', locality_centre=False, grid_type='UKOS', easting=359452, northing=172461, longitude=-2.58489, latitude=51.44967, stop_type='BCT', bus_stop_type='MKD', timing_status='OTH', default_wait_time='', notes='', notes_lang='', administrative_area_code='009', creation_date_time=datetime.datetime(2019, 8, 6, 0, 0), modification_date_time=datetime.datetime(2019, 8, 6, 11, 9, 11), revision_number=120, modification='new', status='active')"),
    GenericRepr("Stop(atco_code='0100BRP90312', naptan_code='bstjaja', plate_code='', cleardown_code='', common_name='Temple Meads Stn', common_name_lang='', short_common_name='Temple Meads Stn', short_common_name_lang='', landmark='', landmark_lang='', street='Station Approach', street_lang='', crossing='', crossing_lang='', indicator='T6', indicator_lang='', bearing='NE', nptg_locality_code='N0077020', nptg_locality_name='Temple Meads', parent_locality_name='', grand_parent_locality_name='', town='', town_lang='', suburb='', suburb_lang='', locality_centre=False, grid_type='UKOS', easting=359609, northing=172383, longitude=-2.58262, latitude=51.44898, stop_type='BCT', bus_stop_type='MKD', timing_status='OTH', default_wait_time='', notes='', notes_lang='', administrative_area_code='009', creation_date_time=datetime.datetime(2009, 8, 25, 0, 0), modification_date_time=datetime.datetime(2020, 11, 26, 13, 23, 29), revision_number=45, modification='new', status='active')"),
    GenericRepr("Stop(atco_code='0100BRP90313', naptan_code='bstjama', plate_code='', cleardown_code='', common_name='Temple Meads Stn', common_name_lang='', short_common_name='Temple Meads Stn', short_common_name_lang='', landmark='', landmark_lang='', street='Station Approach', street_lang='', crossing='', crossing_lang='', indicator='T5', indicator_lang='', bearing='NE', nptg_locality_code='N0077020', nptg_locality_name='Temple Meads', parent_locality_name='', grand_parent_locality_name='', town='', town_lang='', suburb='', suburb_lang='', locality_centre=False, grid_type='UKOS', easting=359669, northing=172433, longitude=-2.58177, latitude=51.44944, stop_type='BCT', bus_stop_type='MKD', timing_status='OTH', default_wait_time='', notes='', notes_lang='', administrative_area_code='009', creation_date_time=datetime.datetime(2009, 8, 25, 0, 0), modification_date_time=datetime.datetime(2020, 11, 26, 13, 22, 13), revision_number=44, modification='new', status='active')"),
    GenericRepr("Stop(atco_code='0100BRP90317', naptan_code='bstjada', plate_code='', cleardown_code='', common_name='Temple Meads Stn', common_name_lang='', short_common_name='Temple Meads Stn', short_common_name_lang='', landmark='', landmark_lang='', street='Temple Gate', street_lang='', crossing='', crossing_lang='', indicator='T1', indicator_lang='', bearing='SE', nptg_locality_code='N0077020', nptg_locality_name='Temple Meads', parent_locality_name='', grand_parent_locality_name='', town='', town_lang='', suburb='', suburb_lang='', locality_centre=False, grid_type='UKOS', easting=359581, northing=172304, longitude=-2.58302, latitude=51.44827, stop_type='BCT', bus_stop_type='MKD', timing_status='OTH', default_wait_time='', notes='', notes_lang='', administrative_area_code='009', creation_date_time=datetime.datetime(2009, 8, 25, 0, 0), modification_date_time=datetime.datetime(2019, 8, 6, 11, 10, 46), revision_number=49, modification='new', status='active')"),
    GenericRepr("Stop(atco_code='0100BRP90318', naptan_code='bstgwtd', plate_code='', cleardown_code='', common_name='Temple Meads Stn', common_name_lang='', short_common_name='Temple Meads Stn', short_common_name_lang='', landmark='', landmark_lang='', street='Redcliffe Way', street_lang='', crossing='', crossing_lang='', indicator='T4', indicator_lang='', bearing='NW', nptg_locality_code='N0077020', nptg_locality_name='Temple Meads', parent_locality_name='', grand_parent_locality_name='', town='', town_lang='', suburb='', suburb_lang='', locality_centre=False, grid_type='UKOS', easting=359439, northing=172371, longitude=-2.58507, latitude=51.44886, stop_type='BCT', bus_stop_type='MKD', timing_status='OTH', default_wait_time='', notes='', notes_lang='', administrative_area_code='009', creation_date_time=datetime.datetime(2009, 8, 25, 0, 0), modification_date_time=datetime.datetime(2019, 8, 6, 11, 11, 5), revision_number=86, modification='new', status='active')"),
    GenericRepr("Stop(atco_code='0100BRA46646', naptan_code='bstpdpm', plate_code='', cleardown_code='', common_name='Old Market Str', common_name_lang='', short_common_name='', short_common_name_lang='', landmark='', landmark_lang='', street='Old Market Street', street_lang='', crossing='', crossing_lang='', indicator='M3', indicator_lang='', bearing='E', nptg_locality_code='N0077040', nptg_locality_name='Old Market', parent_locality_name='', grand_parent_locality_name='', town='', town_lang='', suburb='', suburb_lang='', locality_centre=False, grid_type='UKOS', easting=359635, northing=173156, longitude=-2.58234, latitude=51.45593, stop_type='BCT', bus_stop_type='MKD', timing_status='OTH', default_wait_time='', notes='', notes_lang='', administrative_area_code='009', creation_date_time=datetime.datetime(2007, 3, 14, 0, 0), modification_date_time=datetime.datetime(2018, 7, 18, 13, 43, 1), revision_number=23, modification='new', status='active')"),
    GenericRepr("Stop(atco_code='0100BRA46647', naptan_code='bstpdpt', plate_code='', cleardown_code='', common_name='Old Market Str', common_name_lang='', short_common_name='', short_common_name_lang='', landmark='', landmark_lang='', street='Old Market Street', street_lang='', crossing='', crossing_lang='', indicator='M4', indicator_lang='', bearing='W', nptg_locality_code='N0077040', nptg_locality_name='Old Market', parent_locality_name='', grand_parent_locality_name='', town='', town_lang='', suburb='', suburb_lang='', locality_centre=False, grid_type='UKOS', easting=359706, northing=173174, longitude=-2.58132, latitude=51.4561, stop_type='BCT', bus_stop_type='MKD', timing_status='OTH', default_wait_time='', notes='', notes_lang='', administrative_area_code='009', creation_date_time=datetime.datetime(2007, 3, 14, 0, 0), modification_date_time=datetime.datetime(2018, 6, 11, 14, 45, 46), revision_number=17, modification='new', status='active')")
]
